version: '3.8'

services:
  db:
    build: ./db
    container_name: company-db-2
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: companies
    ports:
      - "5432:5432"
    networks:
      - app_network
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: ./server
    container_name: company-server-2
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: companies
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - app_network

volumes:
  pgdata:

networks:
  app_network:
    driver: bridge
