openapi: 3.0.3
info:
  title: Company Microservice API
  version: 1.0.0
  description: API for managing companies
servers:
  - url: https://api.example.com/v1
    description: Production server
  - url: http://localhost:8080
    description: Local development server

components:
  schemas:
    Company:
      type: object
      required:
        - id
        - name
        - amountOfEmployees
        - registered
        - type
      properties:
        id:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"
        name:
          type: string
          maxLength: 15
          example: "TechCorp"
        description:
          type: string
          maxLength: 3000
          example: "A technology company specializing in AI."
        amountOfEmployees:
          type: integer
          example: 500
        registered:
          type: boolean
          example: true
        type:
          type: string
          enum: [Corporations, NonProfit, Cooperative, Sole Proprietorship]
          example: "Corporations"

paths:
  /companies:
    post:
      summary: Create a new company
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Company'
      responses:
        201:
          description: Company created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'
        400:
          description: Invalid input
  
  /companies/{id}:
    get:
      summary: Get a company by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Company retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'
        404:
          description: Company not found

    patch:
      summary: Update a company
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  maxLength: 15
                description:
                  type: string
                  maxLength: 3000
                amountOfEmployees:
                  type: integer
                registered:
                  type: boolean
                type:
                  type: string
                  enum: [Corporations, NonProfit, Cooperative, Sole Proprietorship]
      responses:
        200:
          description: Company updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'
        400:
          description: Invalid input
        404:
          description: Company not found

    delete:
      summary: Delete a company
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        204:
          description: Company deleted successfully
        404:
          description: Company not found
