openapi: 3.0.0
info:
  title: Token API
  version: 1.0.0
paths:
  /token:
    get:
      summary: Retrieve an authentication token.
      description: Authenticates a user and returns a token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: admin
                password:
                  type: string
                  example: "$2b$12$B.j0F3qX39NVj.gvv.VLCOld/.1FwMUiOsi80l/aUwyfn.ac2wVZa" # Note: In real-world scenarios, do not include example passwords in documentation.
      responses:
        '200':
          description: Successful authentication. Returns a token.
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: The authentication token.
        '401':
          description: Unauthorized. Invalid credentials.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid username or password"
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Internal Server Error"